apiVersion: apps/v1
kind: Deployment
metadata:
  name: httptime-deployment
  labels:
    app: httptime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httptime
  template:
    metadata:
      labels:
        app: httptime
    spec:
      containers:
      - name: httptime
        image: humansriot/httptime:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config.yml
          mountPath: "/root/etc"
          readOnly: true
      volumes:
        - name: config.yml
          configMap:
            name: httptime-config